import type { Metadata } from "next";
import localFont from 'next/font/local';
import Background from "../components/background/Background";
import "../styles/globals.scss";

const mona12 = localFont({
  src: './fonts/Mona12.woff2',
  variable: '--font-mona12',
  display: 'swap',
});

const mona12_blod = localFont({
  src: './fonts/Mona12-Bold.woff2',
  variable: '--font-mona12-Bold',
  display: 'swap',
});

const mona10x12 = localFont({
  src: './fonts/Mona10x12.woff2',
  variable: '--font-mona10x12',
  display: 'swap',
});

const mona10x12_blod = localFont({
  src: './fonts/Mona10x12-Bold.woff2',
  variable: '--font-mona10x12-bold',
  display: 'swap',
});

const powerpuff = localFont({
  src: './fonts/Powerpuff.woff2',
  variable: '--font-powerpuff',
  display: 'swap',
});

const pretendard = localFont({
  src: './fonts/Pretendard-Regular.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`
      ${mona10x12.variable}
      ${mona10x12_blod.variable}
      ${mona12.variable}
      ${mona12_blod.variable}
      ${pretendard.variable}
      ${powerpuff.variable}`}>
      <body>
        <Background />
        {children}
      </body>
    </html>
  );
}
